#!/bin/sh

# Copyright © 2013-2022 Jonathan Vasquez <jon@xyinn.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# Description: A wrapper script around "cantaloupe".

LABEL="$1"
SCRIPT_NAME="cantaloupe"
SCRIPT_PATH="/root/bin"
SCRIPT="${SCRIPT_PATH}/${SCRIPT_NAME}"
BACKUP_POOL="backup"


if [ -z "${LABEL}" ]; then
    echo "You must pass a label in order to start a backup."
    exit 1
fi

if [ ! -f "${SCRIPT}" ]; then
    echo "The backup tool doesn't exist at: ${SCRIPT}. Aborting."
    exit 1
fi

# Check if our pool is imported. We only care about the error code.
zpool status ${BACKUP_POOL} > /dev/null 2>&1

if [ $? -eq 1 ]; then
    echo "The \"${BACKUP_POOL}\" pool is not imported! Aborting."
    exit 1
fi

# Backup each dataset to our backup pool.
"${SCRIPT}" "${BACKUP_POOL}" "${LABEL}" \
tank \
tank/os/main \
tank/home
