#!/bin/sh

# Copyright © 2013-2022 Jonathan Vasquez <jon@xyinn.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

ZFS="/sbin/zfs"

if [ $# -le 1 ]; then
    echo "You must pass the label and dataset to snapshot."
    echo "Example: zfs_snapshot HOURLY tank/os"
    exit
fi

# Get the date so that we can have a stable "seconds" count.
# This will prevent the seconds from being off by a few in between
# different snapshots within our list.
DATE="$(date +%F-%H%M-%S)"

# A label for our snapshots. We can use these labels to quickly label things as
# HOURLY, DAILY, MONTHLY, YEARLY. The label can be whatever you want.
LABEL="$1"
FULL_SNAPSHOT_NAME="${DATE}-${LABEL}"

# Skip the first parameter since the label is stable across all of our snapshots.
shift

while [ "$1" ]; do
    "${ZFS}" snapshot $1@"${FULL_SNAPSHOT_NAME}"
    shift
done
